#!/usr/bin/env ruby
require_relative 'lib/options'
require_relative 'lib/game'

command = ARGV[0]


# name = ARGV[1]
options = Options.parse

case command.downcase
when "add", "remove", "update"
  # User is trying to add, remove or update a game
  name = ARGV[1]
  if name.nil? or name.empty?
    puts "Must provide a name"
    exit
  end
  options[:name] = name
  Game.send(command.to_sym, options)
else
  puts "unknown"
end
